#name: GitHub actions test job
#
## The base action to github which executes the task!
#on: push
#
## All the actions that are set to run!
#jobs: 
#    job_1:
#        runs-on: ubuntu-latest
#        steps:
#            - run: echo hello world!

############################################ Second part of file for the pytest implementation

name: Github actions with pytest

on: [push]

jobs:
    tests:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: Set up Python
              uses: actions/setup-python@v5
              with:
                python-version: '3.13'
            - name: Install Dependencies
              run: |
                python -m pip install --upgrade pip
                pip install .
                pip install -U pytest
                pip install -e .
            - name: Run Pytest
              run: python -m pytest

